# Generated by Django 6.0.3 on 2026-03-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Title')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('request_content', models.TextField(blank=True, default='', verbose_name='Leave Reason')),
                ('status', models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (0, 'Rejected')], default=1, verbose_name='Status')),
                ('response_content', models.TextField(blank=True, default='', verbose_name='Response')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Leave Application',
                'verbose_name_plural': 'Leave Application',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='AbsentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Leave Type')),
            ],
            options={
                'verbose_name': 'Leave Type',
                'verbose_name_plural': 'Leave Type',
            },
        ),
    ]
