# Generated by Django 6.0.3 on 2026-03-16 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('is_top', models.BooleanField(default=False, verbose_name='Is Top')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informs', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcement',
                'ordering': ['-is_top', '-create_time'],
            },
        ),
        migrations.CreateModel(
            name='InformRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_time', models.DateTimeField(auto_now_add=True, verbose_name='Read At')),
                ('inform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_records', to='inform.inform', verbose_name='Announcement')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_informs', to=settings.AUTH_USER_MODEL, verbose_name='Reader')),
            ],
            options={
                'verbose_name': 'Read Record',
                'verbose_name_plural': 'Read Record',
                'unique_together': {('inform', 'reader')},
            },
        ),
    ]
