# Generated by Django 6.0.3 on 2026-03-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inform',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='informs', to='staff.department', verbose_name='Visible Departments'),
        ),
    ]
